spring:
  mail:
    host: mail.hosting.reg.ru
    port: 587
    password: ${EMAIL_PASSWORD}
    username: ${EMAIL_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

emails:
  send-password:
    template: password.html
    subject: "Password for Courses Tools"
  send-email-code:
    template: password.html
    subject: "Code for change email"
  registration:
    template: registration.html
    subject: "Welcome!"
  recovery:
    template: recovery.html
    subject: "Password Recovery"
  trial-start:
    template: trial-start.html
    subject: "Trial period started"
  subscription-expired:
    template: subscription-expired.html
    subject: "Your subscription is suspended"
  trial-end:
    template: trial-end.html
    subject: "Your trial period is over"
  grace-period-end:
    template: grace-period-end.html
    subject: "Your subscription is cancelled"
  subscription-restored:
    template: subscription-restored.html
    subject: "Your Courses Tools subscription is restored"
  first-payment:
    template: first-payment.html
    subject: "Welcome onboard, Partner!"
  payment-retrieve:
    template: payment-retrieve.html
    subject: "Thank you, we’ve received your payment."
